### ISSUE TITLE
Automated Future

### ISSUE THREAD

**Issue by awitherow** [Dcamo001/dcamo001.github.io#21]
# intro, why we need to automate

The biggest problem we are going to run into is with the amount of images you will be having, using the current site setup, there will be continuous need to manually 

1) update the site for each photo
2) adding it to the specific gallery
3) programming the payment available, etc.
4) new deployment

all of this is manual, and could add up to a hour or a few per week depending on how the workflow is for adding new photos.

Secondly, html/css/js is difficult to maintain when there are multiple pages involved, and html markup needs to be edited across multiple pages to ensure it is correctly running and up to date across the whole site. This is not so big of a deal, but just a small pain.

It would be wise to look at a lean option of creating a content management system based approach where you can create galleries, within each gallery would be a photo that would have an automated way to purchase it.

I am looking into the options for setting all this up and I think it can be done relatively cheap in terms of monthly costs. I am not sure how long it would take me to program everything, but I am trying to figure out a way to make that as simple and easy as possible.

# Proposed Solution

1) create a self hosted content management system
2) use next.js for easier automation/programming of automated components
3) use next.js also for frontend/ui reuse

for the first, https://strapi.io looks like a good (hard part)

the second, http://nextjs.org/docs for the site (easy part)

# subtasks

- [ ] test out strapi on desktop, see if will work
- [ ] #22 create content structures necessary for frontend to operate
- [ ] build MVP frontend with payment ability

**Comment by Dcamo001** [comment]
Working on installing strapi, but having trouble getting MongoDB installed

**Comment by awitherow** [comment]
Did you have any luck @Dcamo001 ?  I am going to also attempt to get a local test environment running and see how it looks today.

**Comment by Dcamo001** [comment]
Wasn't able to figure out MongoDB.. might have to watch some videos on it

**Comment by awitherow** [comment]
do the brew installation method for os x, it is easiest.

https://docs.mongodb.com/manual/tutorial/install-mongodb-on-os-x/#install-mongodb-community-edition-with-homebrew

also, it won't be too necessary as we will be running it hosted... https://blog.strapi.io/deploying-a-strapi-api-on-heroku/

I will take care of this and add you to the hosted version.

**Comment by Dcamo001** [comment]
Ok. Either way, I just watched a short video and got mongodb working

**Comment by awitherow** [comment]
Naise, get it running and play around with strapi if you can. This will be what we build the API for your site with. Content Structure is very important. SIMPLE, but if you do one little thing wrong and begin to scale... it exponentiates problems.

**Comment by awitherow** [comment]
created #22 to start brainstorming what is needed for content

**Comment by Dcamo001** [comment]
Getting homebrew installed. That must have been one of the issues... my computer nuked itself a few months ago and I had to restore from a backup but some things didn't carry over I think.

**Comment by Dcamo001** [comment]
So i'm not totally sure what I'm doing but I have everything set up to the end of the strapi guide you sent me

https://dashboard.heroku.com/apps/fathomless-brook-64550
